#NumPy

##Tipos de datos

In [20]:
import numpy as np

#generando un vector de 7 elementos
a=np.array([1,2,3,4,5,6,7])
a
type(a) #clase del vector
a.dtype

dtype('int64')

In [21]:
#generando una matriz de 2 filas y 7 columnas
b=np.array([[1,2,3,4,5,6,7],
            [1,2,3,4,5,6,7]])
b
b.size #número de elementos de b
b.shape #orden de b

(2, 7)

In [22]:
#generando un vector con letras (string)
c=np.array(["hello","bye","hello","bye"])
c.dtype.name

'str160'

##Generando array

In [32]:
#un vector con ceros con shape (3,5)
np.zeros((3,5))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [34]:
#un vector con número aleatorios con shape (3,5)
np.random.random((3,5))

array([[0.53480589, 0.75186789, 0.92252899, 0.92425089, 0.15393556],
       [0.66561628, 0.25010831, 0.006081  , 0.83886327, 0.43465576],
       [0.38612291, 0.79120251, 0.98170928, 0.87531101, 0.93251246]])

In [35]:
#un vector con elementos de 0 a 10 con saltos de 1
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#un vector con 7 elementos del 1 al 10
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

##Operador de incremento

In [44]:
#vector de 7 elementos
a=np.arange(7)
#adición
#a cada elemento del vector se le suma 1
a=a+1
a

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
#adición
a=np.arange(7)
#a cada elemento del vector se le suma 1
a+=1
a

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
#sustracción
a=np.arange(7)
#a cada elemento del vector se le suma 1
a-=1
a

array([-1,  0,  1,  2,  3,  4,  5])

In [47]:
#multiplicación
a=np.arange(7)
#a cada elemento del vector se le suma 1
a*=2
a

array([ 0,  2,  4,  6,  8, 10, 12])

##Promedio y desviación estándar