#NumPy

##Tipos de datos

In [20]:
import numpy as np

#generando un vector de 7 elementos
a=np.array([1,2,3,4,5,6,7])
a
type(a) #clase del vector
a.dtype

dtype('int64')

In [21]:
#generando una matriz de 2 filas y 7 columnas
b=np.array([[1,2,3,4,5,6,7],
            [1,2,3,4,5,6,7]])
b
b.size #número de elementos de b
b.shape #orden de b

(2, 7)

In [22]:
#generando un vector con letras (string)
c=np.array(["hello","bye","hello","bye"])
c.dtype.name

'str160'

##Generando array

In [32]:
#un vector con ceros con shape (3,5)
np.zeros((3,5))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [34]:
#un vector con número aleatorios con shape (3,5)
np.random.random((3,5))

array([[0.53480589, 0.75186789, 0.92252899, 0.92425089, 0.15393556],
       [0.66561628, 0.25010831, 0.006081  , 0.83886327, 0.43465576],
       [0.38612291, 0.79120251, 0.98170928, 0.87531101, 0.93251246]])

In [35]:
#un vector con elementos de 0 a 10 con saltos de 1
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#un vector con 7 elementos del 1 al 10
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

##Operador de incremento

In [44]:
#vector de 7 elementos
a=np.arange(7)
#adición
#a cada elemento del vector se le suma 1
a=a+1
a

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
#adición
a=np.arange(7)
#a cada elemento del vector se le suma 1
a+=1
a

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
#sustracción
a=np.arange(7)
#a cada elemento del vector se le suma 1
a-=1
a

array([-1,  0,  1,  2,  3,  4,  5])

In [47]:
#multiplicación
a=np.arange(7)
#a cada elemento del vector se le suma 1
a*=2
a

array([ 0,  2,  4,  6,  8, 10, 12])

##Promedio y desviación estándar

In [53]:
a=np.arange(1,10,1)
#valor mínimo
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#valor máximo
a.max()

9

In [51]:
#media
a.mean()

5.0

In [55]:
#cálculo manual de media
a.sum()/len(a)

5.0

In [57]:
#mediana
np.median(a)

5.0

In [56]:
#varianza
a.var()

6.666666666666667

In [58]:
#cálculo manual de varianza
sum((a-np.mean(a))**2)/len(a)

6.666666666666667

In [59]:
#desviación estándar
a.std()

2.581988897471611

In [60]:
#cálculo manual de desviación estándar
(sum((a-np.mean(a))**2)/len(a))**0.5

2.581988897471611

#Pandas
##Primer acercamiento a series

In [63]:
import pandas as pd

In [70]:
s=pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [68]:
#seleccionando un elemento dentro de la serie s
#el primer elemento
s[0]

1.0

In [66]:
#seleccionado varios elemento dentro de la serie s
#entre el 1 y 3
s[1:3]

1    2
2    3
dtype: int64

In [71]:
#asignando valores a elementos de las series s
s[0]=.9999
s

0    0.9999
1    2.0000
2    3.0000
3    4.0000
4    5.0000
dtype: float64

In [75]:
#definiendo una serie desde NumPy arrays
arr=np.array([1,2,3,4])
s1=pd.Series(arr)
s1

0    1
1    2
2    3
3    4
dtype: int64

In [78]:
#si cambia el array entonces también cambiará la serie
arr[1]=999
s1

0      1
1    999
2      3
3      4
dtype: int64

In [79]:
#filtrando valores
#valores mayores a 1
s1[s1>1]

1    999
2      3
3      4
dtype: int64

In [80]:
#dividir cada elemento de la serie s por una constante
s1/7

0      0.142857
1    142.714286
2      0.428571
3      0.571429
dtype: float64

In [81]:
#encontrar el log para cada uno de los elementos de la serie s
np.log(s1)

0    0.000000
1    6.906755
2    1.098612
3    1.386294
dtype: float64

In [83]:
#comprendiendo la presencia de valores pérdidos (missing values)
s2=pd.Series([7,8,np.NaN,10,11,np.NaN])
s2

0     7.0
1     8.0
2     NaN
3    10.0
4    11.0
5     NaN
dtype: float64

In [84]:
#dónde están los valores nulos?
s2.isnull()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

##Dataframe

In [91]:
#creando un elemento dataframe de 21 elementos que se distribuyen en 7 filas  y 3 columnas
df=pd.DataFrame(np.arange(21).reshape((7,3)),
                columns=["Econometrics","Calculus","Algebra"])
df

Econometrics  Calculus  Algebra
0             0         1        2
1             3         4        5
2             6         7        8
3             9        10       11
4            12        13       14
5            15        16       17
6            18        19       20

In [93]:
#seleccionado múltiples filas
df.loc[[1,2]]

Econometrics  Calculus  Algebra
1             3         4        5
2             6         7        8

In [96]:
#incorporando nuevas columnas
#Sólo elementos 1
df["Statistical"]=1
df

Econometrics  Calculus  Algebra  Statistical
0             0         1        2            1
1             3         4        5            1
2             6         7        8            1
3             9        10       11            1
4            12        13       14            1
5            15        16       17            1
6            18        19       20            1

In [97]:
#eliminar una columna
del df["Statistical"]
df

Econometrics  Calculus  Algebra
0             0         1        2
1             3         4        5
2             6         7        8
3             9        10       11
4            12        13       14
5            15        16       17
6            18        19       20

In [98]:
#transponer el data frame. Esto no es sinónimo de alterar los valores.
df.T

0  1  2   3   4   5   6
Econometrics  0  3  6   9  12  15  18
Calculus      1  4  7  10  13  16  19
Algebra       2  5  8  11  14  17  20

## Leyendo archivos excel

In [104]:
#cargar un archivo excel al entorno de trabajo en google colab
from google.colab import files
uploaded = files.upload()

Saving df_example.xls to df_example.xls


In [105]:
import io
df=pd.read_excel(io.BytesIO(uploaded["df_example.xls"]))
df

CAP  D&J-CI        A50      IPSA    S&P500 USD/CLP
0    6.180,00  163,37  12.774,33  5.783,11  4.388,71  803,55
1    6.305,00  165,99  13.056,52  5.739,90  4.409,59  793,70
2    6.370,00  165,64  12.953,75  5.741,71  4.425,84  793,13
3    6.420,00  164,95  12.722,39  5.716,29  4.372,59  801,30
4    6.240,00  162,36  12.704,37  5.712,24  4.369,01  803,00
..        ...     ...        ...       ...       ...     ...
784  4.769,10  121,32  14.315,57  4.909,76  3.253,05  757,75
785  4.787,71  120,74  14.452,43  4.913,36  3.237,18  769,12
786  4.833,39  120,63  14.340,98  4.884,39  3.246,28  772,82
787  4.907,15  120,30  14.460,45  4.839,70  3.234,85  763,68
788  4.830,01  121,16  14.531,65  4.804,59  3.257,85  748,63

[789 rows x 6 columns]

##Leyendo archivos csv o archivos de texto


In [111]:
file="https://raw.githubusercontent.com/leomanriquezm/econometrics-course/main/df_text_example.txt"
df=pd.read_table(file,header=1,delim_whitespace=True)
df.head()

Y  X
0  1  3
1  3  4
2  7  1
3  9  3
4  5  1

##Fusionando dataframes